export const DEFAULT_DRIZZLE_CONNECTION_NAME = 'default';
export const DRIZZLE_CLIENT = 'DRIZZLE_CLIENT';
export const DRIZZLE_CONNECTION_MANAGER = 'DRIZZLE_CONNECTION_MANAGER';
export const DRIZZLE_MODULE_OPTIONS = 'DRIZZLE_MODULE_OPTIONS';
export const DRIZZLE_REPOSITORY_METADATA = 'drizzle:repository';
export const DRIZZLE_SCHEMA = 'DRIZZLE_SCHEMA';
export const DRIZZLE_TRANSACTION = 'DRIZZLE_TRANSACTION';
